# GEO-INFER-ACT Example Configuration

# Computational settings
computation:
  device: "cpu"  # "cpu" or "cuda"
  precision: "float32"  # "float32" or "float64"
  random_seed: 42
  num_workers: 4

# Model parameters
active_inference:
  # Default prior precision (confidence)
  prior_precision: 1.0
  
  # Free energy minimization settings
  free_energy:
    algorithm: "variational_laplace"  # Alternatives: "message_passing", "monte_carlo"
    learning_rate: 0.01
    max_iterations: 1000
    convergence_threshold: 1e-5
  
  # Expected free energy parameters for policy selection
  expected_free_energy:
    temp: 1.0  # Precision of policy selection (inverse temperature)
    time_horizon: 5  # How many steps to look ahead
    gamma: 2.0  # Precision of goal-directed behavior
    
# Integration settings
integration:
  space_module: 
    enabled: false
    api_endpoint: "geo_infer_space.api"
  
  time_module:
    enabled: false
    api_endpoint: "geo_infer_time.api"
    
  sim_module:
    enabled: false
    api_endpoint: "geo_infer_sim.api"

# Logging configuration
logging:
  level: "INFO"  # DEBUG, INFO, WARNING, ERROR, CRITICAL
  file: "logs/geo_infer_act.log"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s" 