# Cascadia Agricultural Land Analysis Configuration
# Enhanced with SPACE integration and real data sources

analysis_settings:
  target_counties:
    CA: ["Lassen"]
    OR: []
    WA: []
  
  active_modules:
    - zoning
    - current_use
    - ownership
    - improvements
  
  h3_resolution: 8
  enhanced_visualization: true
  real_time_integration: false
  
  spatial_analysis:
    buffer_distance: 1000  # meters
    proximity_analysis: true
    multi_overlay: true
    correlation_analysis: true
    hotspot_detection: true
  
  data_sources:
    caching_enabled: true
    cache_duration: 86400  # 24 hours
    api_rate_limits:
      requests_per_minute: 60
      requests_per_hour: 1000
  
  visualization:
    base_map: "CartoDB positron"
    default_zoom: 7
    center: [40.5, -120.5]  # Center of Lassen County area
    layers:
      zoning:
        color: "#1f77b4"
        opacity: 0.6
      current_use:
        color: "#2ca02c"
        opacity: 0.6
      water:
        color: "#d62728"
        opacity: 0.6
      ownership:
        color: "#ff7f0e"
        opacity: 0.6
      redevelopment:
        color: "#9467bd"
        opacity: 0.7

# Module-specific configurations
zoning:
  ca_fmmp:
    page_url: "https://www.conservation.ca.gov/dlrp/fmmp/inventory-products"
    latest_year: 2022
  or_dlcd_service_url: "https://maps.oregon.gov/arcgis/rest/services/LandUsePlanning/Statewide_Zoning/FeatureServer/0"
  wa_king_county_service_url: "https://gisdata.kingcounty.gov/arcgis/rest/services/Planning/KingCo_Zoning/MapServer/0"

ownership:
  ca_parcels_service_url: "https://services.gis.ca.gov/arcgis/rest/services/Boundaries/CA_Parcels/FeatureServer/0"

surface_water:
  nhd_flowlines_url: "https://hydro.nationalmap.gov/arcgis/rest/services/NHDPlus_HR/MapServer/1"
  nhd_waterbodies_url: "https://hydro.nationalmap.gov/arcgis/rest/services/NHDPlus_HR/MapServer/2"

current_use:
  nass_cdl_api_url: "https://nassgeodata.gmu.edu/CropScape/nass_data_service.php"
  land_iq_api_url: "https://www.landiq.com/api/v1/parcels"

ground_water:
  nwis_url: "https://waterservices.usgs.gov/nwis/gwlevels/"
  parameter_cd: "72019"

water_rights:
  ca_ewrims_csv_url: "https://data.ca.gov/datastore/dump/e87a4933-2125-4676-928d-294b22c6b44a"

mortgage_debt:
  hmda_bulk_url: "https://ffiec.cfpb.gov/v2/data-browser-api/view/csv?states={state}&years={year}"

power_source:
  hifld_transmission_url: "https://services7.arcgis.com/FGr1D95XCGALwU45/arcgis/rest/services/Electric_Power_Transmission_Lines/FeatureServer/0"
  hifld_power_plants_url: "https://services7.arcgis.com/FGr1D95XCGALwU45/arcgis/rest/services/Power_Plants/FeatureServer/0"

# SPACE integration settings
space_integration:
  osc_geo:
    enabled: true
    repo_path: "../../../GEO-INFER-SPACE/repo"
    h3_loader:
      timeout_seconds: 300
      max_retries: 3
      batch_size: 1000
  
  spatial_processor:
    enabled: true
    buffer_distances: [500, 1000, 2000]  # meters
    correlation_threshold: 0.3
  
  data_integrator:
    enabled: true
    cache_dir: "./cache"
    max_file_size_mb: 100
    compression_enabled: true

# County boundary data sources
county_boundaries:
  ca_lassen:
    name: "Lassen County, CA"
    fips_code: "06035"
    bounds:
      north: 41.2
      south: 40.0
      east: -119.5
      west: -121.5
    data_sources:
      - name: "US Census TIGER/Line"
        url: "https://www2.census.gov/geo/tiger/TIGER2022/COUNTY/tl_2022_06_county.zip"
        format: "shapefile"
      - name: "California State Boundary"
        url: "https://data.ca.gov/dataset/california-county-boundaries"
        format: "geojson"
    geometry_file: "ca_lassen_boundary.geojson" 